(flow-graph :name "python_cfg"
  (nodes
    (block  :id block_1    :label "def main")
    (exit   :id exit_2     :label "return/exit")
    (block  :id block_3    :label "parser = argparse.ArgumentParser(")
    (call   :id call_4     :label "parser.add_argument()")
    (call   :id call_5     :label "parser.add_argument()")
    (call   :id call_6     :label "parser.add_argument()")
    (call   :id call_7     :label "parser.add_argument()")
    (block  :id block_8    :label "args = parser.parse_args()")
    (block  :id block_9    :label "file_path = os.path.abspath(args.file)")
    (fork   :id fork_10    :label "if not os.path.exists(file_path)")
    (virtual :id virtual_11 :label "True")
    (call   :id call_12    :label "print()")
    (call   :id call_13    :label "sys.exit()")
    (join   :id join_14    :label "fi")
    (call   :id call_15    :label "print()")
    (virtual :id virtual_16 :label "try scope")
    (block  :id block_17   :label "engine = ASTEngine()")
    (block  :id block_18   :label "tree, code_bytes = engine.parse_file(...")
    (block  :id block_19   :label "except")
    (join   :id join_20    :label "end try")
    (block  :id block_21   :label "target_node = None")
    (block  :id block_22   :label "root = tree.root_node")
    (block  :id block_23   :label "functions = []")
    (block  :id block_24   :label "ext = file_path.split(\".\")[-1].lower()")
    (block  :id block_25   :label "def find_functions(node, lang_type):")
    (block  :id block_26   :label "builder = None")
    (fork   :id fork_27    :label "if ext == \"rs\"")
    (virtual :id virtual_28 :label "True")
    (block  :id block_29   :label "builder = RustCFGBuilder(code_bytes)")
    (block  :id block_30   :label "functions = find_functions(root, \"rs\")")
    (virtual :id virtual_31 :label "False")
    (fork   :id fork_32    :label "elif ext == \"py\"")
    (virtual :id virtual_33 :label "True")
    (block  :id block_34   :label "builder = PythonCFGBuilder(code_bytes)")
    (block  :id block_35   :label "functions = find_functions(root, \"py\")")
    (join   :id join_36    :label "fi")
    (fork   :id fork_37    :label "if not functions")
    (virtual :id virtual_38 :label "True")
    (call   :id call_39    :label "print()")
    (call   :id call_40    :label "sys.exit()")
    (join   :id join_41    :label "fi")
    (fork   :id fork_42    :label "if args.focus")
    (virtual :id virtual_43 :label "True")
    (fork   :id fork_44    :label "for fn in ...")
    (join   :id join_45    :label "end loop")
    (virtual :id virtual_46 :label "Body")
    (block  :id block_47   :label "name_node = fn.child_by_field_name(\"n...")
    (block  :id block_48   :label "name = code_bytes[name_node.start_byt...")
    (fork   :id fork_49    :label "if name == args.focus")
    (virtual :id virtual_50 :label "True")
    (block  :id block_51   :label "target_node = fn")
    (join   :id join_52    :label "fi")
    (fork   :id fork_53    :label "if not target_node")
    (virtual :id virtual_54 :label "True")
    (call   :id call_55    :label "print()")
    (call   :id call_56    :label "sys.exit()")
    (join   :id join_57    :label "fi")
    (virtual :id virtual_58 :label "False")
    (call   :id call_59    :label "print()")
    (block  :id block_60   :label "target_node = functions[0]")
    (join   :id join_61    :label "fi")
    (block  :id block_62   :label "ulg = builder.build_from_function(tar...")
    (block  :id block_63   :label "base_name = os.path.splitext(file_pat...")
    (block  :id block_64   :label "filename = os.path.basename(base_name)")
    (block  :id block_65   :label "output_dir = f\"{base_name}_logic\"")
    (fork   :id fork_66    :label "if not os.path.exists(output_dir)")
    (virtual :id virtual_67 :label "True")
    (call   :id call_68    :label "os.makedirs()")
    (join   :id join_69    :label "fi")
    (fork   :id fork_70    :label "if args.format in [\"dsl\", \"both\"]")
    (virtual :id virtual_71 :label "True")
    (block  :id block_72   :label "dsl_out = DSLRenderer(ulg).render()")
    (block  :id block_73   :label "dsl_path = os.path.join(output_dir, f...")
    (call   :id call_74    :label "with ...")
    (call   :id call_75    :label "f.write()")
    (virtual :id virtual_76 :label "__exit__")
    (call   :id call_77    :label "print()")
    (join   :id join_78    :label "fi")
    (fork   :id fork_79    :label "if args.format in [\"svg\", \"both\"]")
    (virtual :id virtual_80 :label "True")
    (block  :id block_81   :label "dot_out = DotRenderer(ulg).render()")
    (block  :id block_82   :label "dot_path = os.path.join(output_dir, f...")
    (fork   :id fork_83    :label "if args.svg_dir")
    (virtual :id virtual_84 :label "True")
    (fork   :id fork_85    :label "if not os.path.exists(args.svg_dir)")
    (virtual :id virtual_86 :label "True")
    (call   :id call_87    :label "os.makedirs()")
    (join   :id join_88    :label "fi")
    (block  :id block_89   :label "svg_path = os.path.join(args.svg_dir,...")
    (virtual :id virtual_90 :label "False")
    (block  :id block_91   :label "svg_path = os.path.join(output_dir, f...")
    (join   :id join_92    :label "fi")
    (call   :id call_93    :label "with ...")
    (call   :id call_94    :label "f.write()")
    (virtual :id virtual_95 :label "__exit__")
    (virtual :id virtual_96 :label "try scope")
    (block  :id block_97   :label "import subprocess")
    (call   :id call_98    :label "subprocess.run()")
    (call   :id call_99    :label "print()")
    (block  :id block_100  :label "except")
    (block  :id block_101  :label "except")
    (join   :id join_102   :label "end try")
    (join   :id join_103   :label "fi")
  )
  (edges
    (seq      block_1 -> block_3)
    (seq      block_3 -> call_4)
    (seq      call_4 -> call_5)
    (seq      call_5 -> call_6)
    (seq      call_6 -> call_7)
    (seq      call_7 -> block_8)
    (seq      block_8 -> block_9)
    (seq      block_9 -> fork_10)
    (cond_true fork_10 -> virtual_11 :label "True")
    (cond_false fork_10 -> join_14 :label "False")
    (seq      virtual_11 -> call_12)
    (seq      call_12 -> call_13)
    (seq      call_13 -> join_14)
    (seq      join_14 -> call_15)
    (seq      call_15 -> virtual_16)
    (seq      virtual_16 -> block_17)
    (err      virtual_16 -> block_19 :label "Ex")
    (seq      block_17 -> block_18)
    (seq      block_18 -> join_20)
    (seq      block_19 -> join_20)
    (seq      join_20 -> block_21)
    (seq      block_21 -> block_22)
    (seq      block_22 -> block_23)
    (seq      block_23 -> block_24)
    (seq      block_24 -> block_25)
    (seq      block_25 -> block_26)
    (seq      block_26 -> fork_27)
    (cond_true fork_27 -> virtual_28 :label "True")
    (cond_false fork_27 -> virtual_31 :label "False")
    (seq      virtual_28 -> block_29)
    (seq      block_29 -> block_30)
    (seq      block_30 -> join_36)
    (seq      virtual_31 -> fork_32)
    (cond_true fork_32 -> virtual_33 :label "True")
    (seq      virtual_33 -> block_34)
    (seq      block_34 -> block_35)
    (seq      block_35 -> join_36)
    (seq      join_36 -> fork_37)
    (cond_true fork_37 -> virtual_38 :label "True")
    (cond_false fork_37 -> join_41 :label "False")
    (seq      virtual_38 -> call_39)
    (seq      call_39 -> call_40)
    (seq      call_40 -> join_41)
    (seq      join_41 -> fork_42)
    (cond_true fork_42 -> virtual_43 :label "True")
    (cond_false fork_42 -> virtual_58 :label "False")
    (seq      virtual_43 -> fork_44)
    (cond_true fork_44 -> virtual_46 :label "True")
    (cond_false fork_44 -> join_45 :label "Done")
    (seq      join_45 -> fork_53)
    (seq      virtual_46 -> block_47)
    (seq      block_47 -> block_48)
    (seq      block_48 -> fork_49)
    (cond_true fork_49 -> virtual_50 :label "True")
    (cond_false fork_49 -> join_52 :label "False")
    (seq      virtual_50 -> block_51)
    (jump     block_51 -> join_45 :label "break")
    (jump     join_52 -> fork_44 :label "repeat")
    (cond_true fork_53 -> virtual_54 :label "True")
    (cond_false fork_53 -> join_57 :label "False")
    (seq      virtual_54 -> call_55)
    (seq      call_55 -> call_56)
    (seq      call_56 -> join_57)
    (seq      join_57 -> join_61)
    (seq      virtual_58 -> call_59)
    (seq      call_59 -> block_60)
    (seq      block_60 -> join_61)
    (seq      join_61 -> block_62)
    (seq      block_62 -> block_63)
    (seq      block_63 -> block_64)
    (seq      block_64 -> block_65)
    (seq      block_65 -> fork_66)
    (cond_true fork_66 -> virtual_67 :label "True")
    (cond_false fork_66 -> join_69 :label "False")
    (seq      virtual_67 -> call_68)
    (seq      call_68 -> join_69)
    (seq      join_69 -> fork_70)
    (cond_true fork_70 -> virtual_71 :label "True")
    (cond_false fork_70 -> join_78 :label "False")
    (seq      virtual_71 -> block_72)
    (seq      block_72 -> block_73)
    (seq      block_73 -> call_74)
    (seq      call_74 -> call_75)
    (seq      call_75 -> virtual_76)
    (seq      virtual_76 -> call_77)
    (seq      call_77 -> join_78)
    (seq      join_78 -> fork_79)
    (cond_true fork_79 -> virtual_80 :label "True")
    (cond_false fork_79 -> join_103 :label "False")
    (seq      virtual_80 -> block_81)
    (seq      block_81 -> block_82)
    (seq      block_82 -> fork_83)
    (cond_true fork_83 -> virtual_84 :label "True")
    (cond_false fork_83 -> virtual_90 :label "False")
    (seq      virtual_84 -> fork_85)
    (cond_true fork_85 -> virtual_86 :label "True")
    (cond_false fork_85 -> join_88 :label "False")
    (seq      virtual_86 -> call_87)
    (seq      call_87 -> join_88)
    (seq      join_88 -> block_89)
    (seq      block_89 -> join_92)
    (seq      virtual_90 -> block_91)
    (seq      block_91 -> join_92)
    (seq      join_92 -> call_93)
    (seq      call_93 -> call_94)
    (seq      call_94 -> virtual_95)
    (seq      virtual_95 -> virtual_96)
    (seq      virtual_96 -> block_97)
    (err      virtual_96 -> block_100 :label "Ex")
    (err      virtual_96 -> block_101 :label "Ex")
    (seq      block_97 -> call_98)
    (seq      call_98 -> call_99)
    (seq      call_99 -> join_102)
    (seq      block_100 -> join_102)
    (seq      block_101 -> join_102)
    (seq      join_102 -> join_103)
    (seq      join_103 -> exit_2)
  )
)