(flow-graph :name "python_cfg"
  (nodes
    (block  :id block_1    :label "def main")
    (exit   :id exit_2     :label "return/exit")
    (block  :id block_3    :label "config = ConfigLoader(\"logic_config.y...")
    (block  :id block_4    :label "parser = argparse.ArgumentParser(")
    (call   :id call_5     :label "parser.add_argument()")
    (call   :id call_6     :label "parser.add_argument()")
    (call   :id call_7     :label "parser.add_argument()")
    (call   :id call_8     :label "parser.add_argument()")
    (call   :id call_9     :label "parser.add_argument()")
    (block  :id block_10   :label "args = parser.parse_args()")
    (fork   :id fork_11    :label "if args.config != \"logic_config.yaml\"")
    (virtual :id virtual_12 :label "True")
    (block  :id block_13   :label "config = ConfigLoader(args.config)")
    (join   :id join_14    :label "fi")
    (block  :id block_15   :label "file_path = os.path.abspath(args.file)")
    (fork   :id fork_16    :label "if not os.path.exists(file_path)")
    (virtual :id virtual_17 :label "True")
    (call   :id call_18    :label "print()")
    (call   :id call_19    :label "sys.exit()")
    (join   :id join_20    :label "fi")
    (call   :id call_21    :label "print()")
    (virtual :id virtual_22 :label "try scope")
    (block  :id block_23   :label "engine = ASTEngine()")
    (block  :id block_24   :label "tree, code_bytes = engine.parse_file(...")
    (block  :id block_25   :label "except")
    (join   :id join_26    :label "end try")
    (block  :id block_27   :label "target_node = None")
    (block  :id block_28   :label "root = tree.root_node")
    (block  :id block_29   :label "functions = []")
    (block  :id block_30   :label "ext = file_path.split(\".\")[-1].lower()")
    (block  :id block_31   :label "def find_functions(node, lang_type):")
    (block  :id block_32   :label "builder = None")
    (fork   :id fork_33    :label "if ext == \"rs\"")
    (virtual :id virtual_34 :label "True")
    (block  :id block_35   :label "builder = RustCFGBuilder(code_bytes)")
    (block  :id block_36   :label "functions = find_functions(root, \"rs\")")
    (virtual :id virtual_37 :label "False")
    (fork   :id fork_38    :label "elif ext == \"py\"")
    (virtual :id virtual_39 :label "True")
    (block  :id block_40   :label "builder = PythonCFGBuilder(code_bytes)")
    (block  :id block_41   :label "functions = find_functions(root, \"py\")")
    (join   :id join_42    :label "fi")
    (fork   :id fork_43    :label "if hasattr(builder, \"set_config_loader\")")
    (virtual :id virtual_44 :label "True")
    (call   :id call_45    :label "builder.set_config_loader()")
    (join   :id join_46    :label "fi")
    (fork   :id fork_47    :label "if not functions")
    (virtual :id virtual_48 :label "True")
    (call   :id call_49    :label "print()")
    (call   :id call_50    :label "sys.exit()")
    (join   :id join_51    :label "fi")
    (fork   :id fork_52    :label "if args.focus")
    (virtual :id virtual_53 :label "True")
    (fork   :id fork_54    :label "for fn in ...")
    (join   :id join_55    :label "end loop")
    (virtual :id virtual_56 :label "Body")
    (block  :id block_57   :label "name_node = fn.child_by_field_name(\"n...")
    (block  :id block_58   :label "name = code_bytes[name_node.start_byt...")
    (fork   :id fork_59    :label "if name == args.focus")
    (virtual :id virtual_60 :label "True")
    (block  :id block_61   :label "target_node = fn")
    (join   :id join_62    :label "fi")
    (fork   :id fork_63    :label "if not target_node")
    (virtual :id virtual_64 :label "True")
    (call   :id call_65    :label "print()")
    (call   :id call_66    :label "sys.exit()")
    (join   :id join_67    :label "fi")
    (virtual :id virtual_68 :label "False")
    (call   :id call_69    :label "print()")
    (block  :id block_70   :label "target_node = functions[0]")
    (join   :id join_71    :label "fi")
    (block  :id block_72   :label "ulg = builder.build_from_function(tar...")
    (block  :id block_73   :label "base_name = os.path.splitext(file_pat...")
    (block  :id block_74   :label "filename = os.path.basename(base_name)")
    (block  :id block_75   :label "output_dir = f\"{base_name}_logic\"")
    (fork   :id fork_76    :label "if not os.path.exists(output_dir)")
    (virtual :id virtual_77 :label "True")
    (call   :id call_78    :label "os.makedirs()")
    (join   :id join_79    :label "fi")
    (fork   :id fork_80    :label "if args.format in [\"dsl\", \"both\"]")
    (virtual :id virtual_81 :label "True")
    (block  :id block_82   :label "dsl_out = DSLRenderer(ulg).render()")
    (block  :id block_83   :label "dsl_path = os.path.join(output_dir, f...")
    (call   :id call_84    :label "with ...")
    (call   :id call_85    :label "f.write()")
    (virtual :id virtual_86 :label "__exit__")
    (call   :id call_87    :label "print()")
    (join   :id join_88    :label "fi")
    (fork   :id fork_89    :label "if args.format in [\"svg\", \"both\"]")
    (virtual :id virtual_90 :label "True")
    (block  :id block_91   :label "dot_out = DotRenderer(ulg).render()")
    (block  :id block_92   :label "dot_path = os.path.join(output_dir, f...")
    (fork   :id fork_93    :label "if args.svg_dir")
    (virtual :id virtual_94 :label "True")
    (fork   :id fork_95    :label "if not os.path.exists(args.svg_dir)")
    (virtual :id virtual_96 :label "True")
    (call   :id call_97    :label "os.makedirs()")
    (join   :id join_98    :label "fi")
    (block  :id block_99   :label "svg_path = os.path.join(args.svg_dir,...")
    (virtual :id virtual_100 :label "False")
    (block  :id block_101  :label "svg_path = os.path.join(output_dir, f...")
    (join   :id join_102   :label "fi")
    (call   :id call_103   :label "with ...")
    (call   :id call_104   :label "f.write()")
    (virtual :id virtual_105 :label "__exit__")
    (virtual :id virtual_106 :label "try scope")
    (block  :id block_107  :label "import subprocess")
    (call   :id call_108   :label "subprocess.run()")
    (call   :id call_109   :label "print()")
    (block  :id block_110  :label "except")
    (block  :id block_111  :label "except")
    (join   :id join_112   :label "end try")
    (join   :id join_113   :label "fi")
  )
  (edges
    (seq      block_1 -> block_3)
    (seq      block_3 -> block_4)
    (seq      block_4 -> call_5)
    (seq      call_5 -> call_6)
    (seq      call_6 -> call_7)
    (seq      call_7 -> call_8)
    (seq      call_8 -> call_9)
    (seq      call_9 -> block_10)
    (seq      block_10 -> fork_11)
    (cond_true fork_11 -> virtual_12 :label "True")
    (cond_false fork_11 -> join_14 :label "False")
    (seq      virtual_12 -> block_13)
    (seq      block_13 -> join_14)
    (seq      join_14 -> block_15)
    (seq      block_15 -> fork_16)
    (cond_true fork_16 -> virtual_17 :label "True")
    (cond_false fork_16 -> join_20 :label "False")
    (seq      virtual_17 -> call_18)
    (seq      call_18 -> call_19)
    (seq      call_19 -> join_20)
    (seq      join_20 -> call_21)
    (seq      call_21 -> virtual_22)
    (seq      virtual_22 -> block_23)
    (err      virtual_22 -> block_25 :label "Ex")
    (seq      block_23 -> block_24)
    (seq      block_24 -> join_26)
    (seq      block_25 -> join_26)
    (seq      join_26 -> block_27)
    (seq      block_27 -> block_28)
    (seq      block_28 -> block_29)
    (seq      block_29 -> block_30)
    (seq      block_30 -> block_31)
    (seq      block_31 -> block_32)
    (seq      block_32 -> fork_33)
    (cond_true fork_33 -> virtual_34 :label "True")
    (cond_false fork_33 -> virtual_37 :label "False")
    (seq      virtual_34 -> block_35)
    (seq      block_35 -> block_36)
    (seq      block_36 -> join_42)
    (seq      virtual_37 -> fork_38)
    (cond_true fork_38 -> virtual_39 :label "True")
    (seq      virtual_39 -> block_40)
    (seq      block_40 -> block_41)
    (seq      block_41 -> join_42)
    (seq      join_42 -> fork_43)
    (cond_true fork_43 -> virtual_44 :label "True")
    (cond_false fork_43 -> join_46 :label "False")
    (seq      virtual_44 -> call_45)
    (seq      call_45 -> join_46)
    (seq      join_46 -> fork_47)
    (cond_true fork_47 -> virtual_48 :label "True")
    (cond_false fork_47 -> join_51 :label "False")
    (seq      virtual_48 -> call_49)
    (seq      call_49 -> call_50)
    (seq      call_50 -> join_51)
    (seq      join_51 -> fork_52)
    (cond_true fork_52 -> virtual_53 :label "True")
    (cond_false fork_52 -> virtual_68 :label "False")
    (seq      virtual_53 -> fork_54)
    (cond_true fork_54 -> virtual_56 :label "True")
    (cond_false fork_54 -> join_55 :label "Done")
    (seq      join_55 -> fork_63)
    (seq      virtual_56 -> block_57)
    (seq      block_57 -> block_58)
    (seq      block_58 -> fork_59)
    (cond_true fork_59 -> virtual_60 :label "True")
    (cond_false fork_59 -> join_62 :label "False")
    (seq      virtual_60 -> block_61)
    (jump     block_61 -> join_55 :label "break")
    (jump     join_62 -> fork_54 :label "repeat")
    (cond_true fork_63 -> virtual_64 :label "True")
    (cond_false fork_63 -> join_67 :label "False")
    (seq      virtual_64 -> call_65)
    (seq      call_65 -> call_66)
    (seq      call_66 -> join_67)
    (seq      join_67 -> join_71)
    (seq      virtual_68 -> call_69)
    (seq      call_69 -> block_70)
    (seq      block_70 -> join_71)
    (seq      join_71 -> block_72)
    (seq      block_72 -> block_73)
    (seq      block_73 -> block_74)
    (seq      block_74 -> block_75)
    (seq      block_75 -> fork_76)
    (cond_true fork_76 -> virtual_77 :label "True")
    (cond_false fork_76 -> join_79 :label "False")
    (seq      virtual_77 -> call_78)
    (seq      call_78 -> join_79)
    (seq      join_79 -> fork_80)
    (cond_true fork_80 -> virtual_81 :label "True")
    (cond_false fork_80 -> join_88 :label "False")
    (seq      virtual_81 -> block_82)
    (seq      block_82 -> block_83)
    (seq      block_83 -> call_84)
    (seq      call_84 -> call_85)
    (seq      call_85 -> virtual_86)
    (seq      virtual_86 -> call_87)
    (seq      call_87 -> join_88)
    (seq      join_88 -> fork_89)
    (cond_true fork_89 -> virtual_90 :label "True")
    (cond_false fork_89 -> join_113 :label "False")
    (seq      virtual_90 -> block_91)
    (seq      block_91 -> block_92)
    (seq      block_92 -> fork_93)
    (cond_true fork_93 -> virtual_94 :label "True")
    (cond_false fork_93 -> virtual_100 :label "False")
    (seq      virtual_94 -> fork_95)
    (cond_true fork_95 -> virtual_96 :label "True")
    (cond_false fork_95 -> join_98 :label "False")
    (seq      virtual_96 -> call_97)
    (seq      call_97 -> join_98)
    (seq      join_98 -> block_99)
    (seq      block_99 -> join_102)
    (seq      virtual_100 -> block_101)
    (seq      block_101 -> join_102)
    (seq      join_102 -> call_103)
    (seq      call_103 -> call_104)
    (seq      call_104 -> virtual_105)
    (seq      virtual_105 -> virtual_106)
    (seq      virtual_106 -> block_107)
    (err      virtual_106 -> block_110 :label "Ex")
    (err      virtual_106 -> block_111 :label "Ex")
    (seq      block_107 -> call_108)
    (seq      call_108 -> call_109)
    (seq      call_109 -> join_112)
    (seq      block_110 -> join_112)
    (seq      block_111 -> join_112)
    (seq      join_112 -> join_113)
    (seq      join_113 -> exit_2)
  )
)