(flow-graph :name "rust_cfg"
  (nodes
    (block  :id block_1    :label "fn complex_logic")
    (exit   :id exit_2     :label "Function Exit")
    (virtual :id virtual_3  :label "Check '?'")
    (block  :id block_4    :label "let start = check_start(x)?;")
    (fork   :id fork_5     :label "if start > 100")
    (exit   :id exit_6     :label "return")
    (block  :id block_7    :label "else {")
    (join   :id join_8     :label "fi")
    (block  :id block_9    :label "let mut count = 0;")
    (join   :id join_10    :label "loop")
    (join   :id join_11    :label "end loop")
    (block  :id block_12   :label "count += 1")
    (fork   :id fork_13    :label "if count > 5")
    (join   :id join_14    :label "fi")
    (fork   :id fork_15    :label "if count == 2")
    (join   :id join_16    :label "fi")
    (block  :id block_17   :label "println!(\"Looping\")")
    (fork   :id fork_18    :label "match count")
    (join   :id join_19    :label "end match")
    (block  :id block_20   :label "println!(\"One\")")
    (block  :id block_21   :label "println!(\"Two\")")
    (exit   :id exit_22    :label "return")
    (block  :id block_23   :label "Ok(count)")
  )
  (edges
    (seq      block_1 -> virtual_3)
    (err      virtual_3 -> exit_2 :label "Err")
    (seq      virtual_3 -> block_4)
    (seq      block_4 -> fork_5)
    (seq      fork_5 -> exit_6)
    (cond_false fork_5 -> block_7 :label "False")
    (seq      exit_6 -> exit_2)
    (seq      block_7 -> join_8)
    (seq      join_8 -> block_9)
    (seq      block_9 -> join_10)
    (seq      join_10 -> block_12)
    (seq      join_11 -> fork_18)
    (seq      block_12 -> fork_13)
    (jump     fork_13 -> join_11 :label "break")
    (cond_false fork_13 -> join_14 :label "False")
    (seq      join_14 -> fork_15)
    (jump     fork_15 -> join_10 :label "continue")
    (cond_false fork_15 -> join_16 :label "False")
    (seq      join_16 -> block_17)
    (jump     block_17 -> join_10 :label "repeat")
    (cond_true fork_18 -> block_20 :label "1")
    (cond_true fork_18 -> block_21 :label "2")
    (cond_true fork_18 -> exit_22 :label "_")
    (seq      join_19 -> block_23)
    (seq      block_20 -> join_19)
    (seq      block_21 -> join_19)
    (seq      exit_22 -> exit_2)
    (seq      block_23 -> exit_2)
  )
)