(flow-graph :name "rust_cfg"
  (nodes
    (block  :id block_1    :label "fn complex_logic")
    (exit   :id exit_2     :label "Function Exit")
    (virtual :id virtual_3  :label "Check '?'")
    (block  :id block_4    :label "let start = check_start(x)?;")
    (fork   :id fork_5     :label "if start > 100")
    (block  :id block_6    :label "Then")
    (virtual :id virtual_7  :label "True")
    (exit   :id exit_8     :label "return")
    (virtual :id virtual_9  :label "False")
    (block  :id block_10   :label "else {")
    (join   :id join_11    :label "fi")
    (block  :id block_12   :label "let mut count = 0;")
    (join   :id join_13    :label "loop")
    (join   :id join_14    :label "end loop")
    (block  :id block_15   :label "count += 1")
    (fork   :id fork_16    :label "if count > 5")
    (block  :id block_17   :label "Then")
    (virtual :id virtual_18 :label "True")
    (join   :id join_19    :label "fi")
    (fork   :id fork_20    :label "if count == 2")
    (block  :id block_21   :label "Then")
    (virtual :id virtual_22 :label "True")
    (join   :id join_23    :label "fi")
    (block  :id block_24   :label "println!(\"Looping\")")
    (fork   :id fork_25    :label "match count")
    (join   :id join_26    :label "end match")
    (virtual :id virtual_27 :label "Case 1")
    (block  :id block_28   :label "println!(\"One\")")
    (virtual :id virtual_29 :label "Case 2")
    (block  :id block_30   :label "println!(\"Two\")")
    (virtual :id virtual_31 :label "Case _")
    (exit   :id exit_32    :label "return")
    (block  :id block_33   :label "Ok(count)")
  )
  (edges
    (seq      block_1 -> virtual_3)
    (err      virtual_3 -> exit_2 :label "Err")
    (seq      virtual_3 -> block_4)
    (seq      block_4 -> fork_5)
    (cond_true fork_5 -> virtual_7 :label "True")
    (cond_false fork_5 -> virtual_9 :label "False")
    (seq      virtual_7 -> exit_8)
    (seq      exit_8 -> exit_2)
    (seq      virtual_9 -> block_10)
    (seq      block_10 -> join_11)
    (seq      join_11 -> block_12)
    (seq      block_12 -> join_13)
    (seq      join_13 -> block_15)
    (seq      join_14 -> fork_25)
    (seq      block_15 -> fork_16)
    (cond_true fork_16 -> virtual_18 :label "True")
    (cond_false fork_16 -> join_19 :label "False")
    (jump     virtual_18 -> join_14 :label "break")
    (seq      join_19 -> fork_20)
    (cond_true fork_20 -> virtual_22 :label "True")
    (cond_false fork_20 -> join_23 :label "False")
    (jump     virtual_22 -> join_13 :label "continue")
    (seq      join_23 -> block_24)
    (jump     block_24 -> join_13 :label "repeat")
    (cond_true fork_25 -> virtual_27 :label "1")
    (cond_true fork_25 -> virtual_29 :label "2")
    (cond_true fork_25 -> virtual_31 :label "_")
    (seq      join_26 -> block_33)
    (seq      virtual_27 -> block_28)
    (seq      block_28 -> join_26)
    (seq      virtual_29 -> block_30)
    (seq      block_30 -> join_26)
    (seq      virtual_31 -> exit_32)
    (seq      exit_32 -> exit_2)
    (seq      block_33 -> exit_2)
  )
)